import { AccountCard } from "@/components/AccountCard";
import { Card } from "@/components/Cards";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import { CreditCardIcon } from "@heroicons/react/24/outline";

const inter = Inter({ subsets: ["latin"] });

const card_WG = {
  name: "Living Community",
  href: "/LivingCommunityAccount",
  icon: CreditCardIcon,
  amount: "€ 2,400.50",
  description: "My Living Community in Vienna",
};

const card_Family = {
  name: "Family",
  href: "/Family",
  icon: CreditCardIcon,
  amount: "€ 5,600.50",
  description: "My shared family account",
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Loyalty Mockup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2 className="text-lg font-medium leading-6 text-gray-900 mt-8 ml-6">
          Wallet Overview
        </h2>

        <AccountCard card={card_WG} />
        <AccountCard card={card_Family} />
        {/* <button
          type="button"
          className="inline-flex items-center px-3 py-2 text-sm font-semibold text-white rounded-md shadow-sm bg-cyan-600 hover:bg-cyan-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-600"
        >
          Send money
        </button> */}
      </div>
    </>
  );
}
