import { AccountCard } from "@/components/AccountCard";
import { Profile } from "@/components/Profile";
import Tabbar from "@/components/Tabbar";
import { CreditCardIcon, PlusCircleIcon } from "@heroicons/react/24/outline";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";
import MyAccount from "./MyAccount";

const inter = Inter({ subsets: ["latin"] });

const card_WG = {
  name: "Living Community",
  href: "/LivingCommunityAccount",
  icon: CreditCardIcon,
  amount: "€ 2,400.50",
  description: "Bennogasse 19/19",
};

const card_Family = {
  name: "Family",
  href: "/Family",
  icon: CreditCardIcon,
  amount: "€ 5,600.50",
  description: "My shared family account",
};

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Loyalty Mockup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-8">
        <Profile />
        <MyAccount />
        <div className="flex content-center justify-between">
          <h2 className="mt-8 ml-6 leading-6 text-gray-900 font-md">
            Shared Wallets
          </h2>
          <div
            className="flex justify-end"
            onClick={() => router.push("/create")}
          >
            <PlusCircleIcon className="w-8 h-8 mr-6 text-gray-500" />
          </div>
        </div>
        <div className="mb-52">
          <AccountCard card={card_WG} />
          <AccountCard card={card_Family} />
        </div>
        <Tabbar />
      </div>
    </>
  );
}
