/* eslint-disable @next/next/no-img-element */
import { AccountCard } from "@/components/AccountCard";
import { Card } from "@/components/Cards";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import Image from "next/image";
import {
  BanknotesIcon,
  ChevronRightIcon,
  CreditCardIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  ShoppingBagIcon,
} from "@heroicons/react/24/outline";

const transactions = [
  {
    id: 1,
    name: "Payment to Molly Sanders",
    href: "#",
    amount: "€ 20,000.00",
    currency: "EUR",
    status: "success",
    date: "July 11, 2023",
    datetime: "2023-07-11",
  },
  {
    id: 2,
    name: "Payment to Supermarket",
    href: "#",
    amount: "€ 44.23",
    currency: "USD",
    status: "success",
    date: "July 12, 2023",
    datetime: "2023-07-11",
  },
  {
    id: 3,
    name: "Payment to Phone carrier",
    href: "#",
    amount: "€ 10.99",
    currency: "EUR",
    status: "success",
    date: "July 13, 2023",
    datetime: "2023-07-11",
  },
  // More transactions...
];

export default function LivingCommunityAccount() {
  return (
    <>
      <Head>
        <title>Living Community Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h2 className="text-lg font-large leading-6 text-gray-900 mt-8 ml-6">
          Living Community
        </h2>
        <h2 className="text-lg font-medium leading-6 text-gray-900 mt-8 ml-6 text-center">
          € 2,400.50
        </h2>

        <div className="flex justify-center align-middle gap-40 m-10">
          <button
            type="button"
            className="inline-flex items-center px-3 py-2 text-sm font-semibold text-gray-900 bg-white rounded-md shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
          >
            Deposit{" "}
            <ArrowDownIcon className="flex-shrink-0 w-5 h-5 text-gray-400 ml-5 " />
          </button>
          <button
            type="button"
            className="inline-flex items-center px-3 py-2 text-sm font-semibold text-white rounded-md shadow-sm bg-cyan-600 hover:bg-cyan-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-600"
          >
            Withdraw{" "}
            <ArrowUpIcon className="flex-shrink-0 w-5 h-5 text-white-400 ml-5 " />
          </button>
        </div>

        <div className="flex items-center   bg-blue-600     px-3 py-2 text-sm  shadow-sm ring-1 ring-inset ring-blue-700 hover:bg-blue-700 mt-2 rounded text-center m-20">
          Claim new offers
          <ShoppingBagIcon className="flex-shrink-0 w-5 h-5 text-gray-400 ml-5 " />
        </div>

        <h2 className="max-w-6xl px-4 mx-auto mt-8 text-lg font-medium leading-6 text-gray-900 sm:px-6 lg:px-8">
          Members
        </h2>

        <div className="m-2">
          <div className="flex items-center   bg-white rounded-md shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 mt-2">
            <img
              className="w-12 h-12 rounded-full sm:hidden m-3"
              src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
              alt=""
            />
            <h1 className="text-small  leading-7 text-gray-900 sm:truncate sm:leading-9 mr-10 ml-10">
              John Doe
            </h1>
          </div>
          <div className="flex items-center   bg-white rounded-md shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50 mt-2">
            <img
              className="w-12 h-12 rounded-full sm:hidden m-3"
              src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.6&w=256&h=256&q=80"
              alt=""
            />
            <h1 className="text-small  leading-7 text-gray-900 sm:truncate sm:leading-9 mr-10 ml-10">
              Lisa Stone
            </h1>
          </div>
        </div>

        <h2 className="max-w-6xl px-4 mx-auto mt-8 text-lg font-medium leading-6 text-gray-900 sm:px-6 lg:px-8">
          Recent activity
        </h2>

        {/* Activity list (smallest breakpoint only) */}
        <div className="shadow sm:hidden">
          <ul
            role="list"
            className="mt-2 overflow-hidden divide-y divide-gray-200 shadow sm:hidden"
          >
            {transactions.map((transaction) => (
              <li key={transaction.id}>
                <a
                  href={transaction.href}
                  className="block px-4 py-4 bg-white hover:bg-gray-50"
                >
                  <span className="flex items-center space-x-4">
                    <span className="flex flex-1 space-x-2 truncate">
                      <BanknotesIcon
                        className="flex-shrink-0 w-5 h-5 text-gray-400"
                        aria-hidden="true"
                      />
                      <span className="flex flex-col text-sm text-gray-500 truncate">
                        <span className="truncate">{transaction.name}</span>
                        <span>
                          <span className="font-medium text-gray-900">
                            {transaction.amount}
                          </span>{" "}
                          {transaction.currency}
                        </span>
                        <time dateTime={transaction.datetime}>
                          {transaction.date}
                        </time>
                      </span>
                    </span>
                    <ChevronRightIcon
                      className="flex-shrink-0 w-5 h-5 text-gray-400"
                      aria-hidden="true"
                    />
                  </span>
                </a>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </>
  );
}
