/* eslint-disable @next/next/no-img-element */
import {
  ArrowDownIcon,
  ArrowUpIcon,
  BanknotesIcon,
  ChevronRightIcon,
} from "@heroicons/react/24/outline";
import Head from "next/head";

const transactions = [
  {
    id: 1,
    name: "Payment to Molly Sanders",
    href: "#",
    amount: "€ 2,000.00",
    currency: "EUR",
    status: "success",
    date: "July 11, 2023",
    datetime: "2023-07-11",
  },
  {
    id: 2,
    name: "Payment to Supermarket",
    href: "#",
    amount: "€ 44.23",
    currency: "USD",
    status: "success",
    date: "July 12, 2023",
    datetime: "2023-07-11",
  },
  {
    id: 3,
    name: "Payment to Phone carrier",
    href: "#",
    amount: "€ 10.99",
    currency: "EUR",
    status: "success",
    date: "July 13, 2023",
    datetime: "2023-07-11",
  },
  // More transactions...
];

export default function MyAccount() {
  return (
    <>
      <Head>
        <title>My Account - Overview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* <h2 className="mt-8 ml-6 text-lg leading-6 text-center text-gray-900 font-lg">
          My Account
        </h2> */}
        <h2 className="mt-8 ml-6 text-2xl font-semibold leading-6 text-center text-gray-900">
          € 2,400.50
        </h2>

        <div className="flex justify-between m-10 align-middle">
          <button
            type="button"
            className="inline-flex items-center px-3 py-2 text-sm font-semibold text-gray-900 bg-white rounded-md shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
          >
            Deposit{" "}
            <ArrowDownIcon className="flex-shrink-0 w-5 h-5 ml-5 text-gray-400 " />
          </button>
          <button
            type="button"
            className="inline-flex items-center px-3 py-2 text-sm font-semibold text-white rounded-md shadow-sm bg-cyan-600 hover:bg-cyan-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-600"
          >
            Withdraw{" "}
            <ArrowUpIcon className="flex-shrink-0 w-5 h-5 ml-5 text-white-400 " />
          </button>
        </div>

        <h2 className="max-w-6xl px-4 mx-auto mt-8 text-lg font-medium leading-6 text-gray-900 sm:px-6 lg:px-8">
          Recent activity
        </h2>

        {/* Activity list (smallest breakpoint only) */}
        <div className="mt-2 shadow sm:hidden">
          <ul
            role="list"
            className="overflow-hidden divide-y divide-gray-200 shadow sm:hidden"
          >
            {transactions.map((transaction) => (
              <li key={transaction.id}>
                <a
                  href={transaction.href}
                  className="block px-4 py-4 bg-white hover:bg-gray-50"
                >
                  <span className="flex items-center space-x-4">
                    <span className="flex flex-1 space-x-2 truncate">
                      <BanknotesIcon
                        className="flex-shrink-0 w-5 h-5 text-gray-400"
                        aria-hidden="true"
                      />
                      <span className="flex flex-col text-sm text-gray-500 truncate">
                        <span className="truncate">{transaction.name}</span>
                        <span>
                          <span className="font-medium text-gray-900">
                            {transaction.amount}
                          </span>{" "}
                          {transaction.currency}
                        </span>
                        <time dateTime={transaction.datetime}>
                          {transaction.date}
                        </time>
                      </span>
                    </span>
                    <ChevronRightIcon
                      className="flex-shrink-0 w-5 h-5 text-gray-400"
                      aria-hidden="true"
                    />
                  </span>
                </a>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </>
  );
}
